import { useEffect, useState } from 'react';
import api from '../api/axios';
import { exportToCSV, exportToPDF } from '../utils/exportUtils';

export default function Alerts() {
  const [rows, setRows] = useState([]);
  const [history, setHistory] = useState([]);
  const [activeTab, setActiveTab] = useState('active'); // 'active' or 'history'
  
  // Resolution Modal state
  const [resolveId, setResolveId] = useState(null);
  const [note, setNote] = useState('');
  const [assigned, setAssigned] = useState('');

  const role = localStorage.getItem('role') || 'viewer';
  const isAdmin = role.toLowerCase() === 'admin';

  const loadActive = () => api.get('/alerts').then((r) => setRows(r.data));
  const loadHistory = () => api.get('/alerts/history').then((r) => setHistory(r.data));

  useEffect(() => {
    loadActive();
    loadHistory();
  }, []);

  const openResolveModal = (id) => {
    setResolveId(id);
    setNote('');
    setAssigned('');
  };

  const handleResolve = async (e) => {
    e.preventDefault();
    if (!isAdmin) return;
    await api.put(`/alerts/${resolveId}/resolve`, {
      resolution_note: note,
      assigned_to: assigned
    });
    setResolveId(null);
    loadActive();
    loadHistory();
  };

  const getSeverityBadge = (sev) => {
    switch (sev) {
      case 'HIGH': return 'bg-danger text-light';
      case 'MEDIUM': return 'bg-warning text-dark';
      case 'LOW': return 'bg-info text-dark';
      default: return 'bg-secondary';
    }
  };

  const handleExportCSV = () => {
    const data = activeTab === 'active' ? rows : history;
    const exportData = data.map(r => ({
      'Alert ID': r.alert_id,
      'Well': r.well_name,
      District: r.district,
      Severity: r.severity,
      Message: r.message,
      Created: r.created_at,
      Status: r.status,
      'Assigned To': r.assigned_to || '—',
      'Resolution Note': r.resolution_note || '—',
      'Resolved At': r.resolved_at || '—'
    }));
    exportToCSV(exportData, `alerts_${activeTab}_report`);
  };

  const handleExportPDF = () => {
    const data = activeTab === 'active' ? rows : history;
    const headers = ['ID', 'Well Name', 'District', 'Severity', 'Alert message description', 'Date & Time'];
    const dataRows = data.map(r => [
      r.alert_id,
      r.well_name,
      r.district,
      r.severity,
      r.message,
      new Date(r.created_at).toLocaleString()
    ]);
    const summaryStats = {
      'Total Alerts Count': data.length,
      'High Severity Count': data.filter(r => r.severity === 'HIGH').length,
      'Medium Severity Count': data.filter(r => r.severity === 'MEDIUM').length
    };
    exportToPDF(`${activeTab === 'active' ? 'Active Alerts' : 'Alerts History'} Report`, headers, dataRows, summaryStats);
  };

  return (
    <div>
      <div className="d-flex justify-content-between align-items-center mb-4">
        <div>
          <h1 className="fw-bold mb-1 text-dark">Alerts Management</h1>
          <p className="text-secondary small">Automatically generated by MySQL triggers when depth exceeds threshold limit.</p>
        </div>
        <div className="d-flex gap-2">
          <button className="btn btn-outline-primary btn-sm fw-semibold shadow-sm px-3" onClick={handleExportCSV}>
            Export CSV
          </button>
          <button className="btn btn-primary btn-sm fw-semibold shadow-sm px-3" onClick={handleExportPDF}>
            Export PDF
          </button>
        </div>
      </div>

      {/* Tabs Menu */}
      <ul className="nav nav-tabs mb-4 border-bottom border-secondary-subtle">
        <li className="nav-item">
          <button 
            className={`nav-link fw-bold px-4 py-2.5 ${activeTab === 'active' ? 'active text-primary' : 'text-secondary'}`}
            onClick={() => setActiveTab('active')}
          >
            Active Alerts ({rows.length})
          </button>
        </li>
        <li className="nav-item">
          <button 
            className={`nav-link fw-bold px-4 py-2.5 ${activeTab === 'history' ? 'active text-primary' : 'text-secondary'}`}
            onClick={() => setActiveTab('history')}
          >
            Resolved History ({history.length})
          </button>
        </li>
      </ul>

      {/* Grid displays based on selected active tab */}
      {activeTab === 'active' ? (
        <div className="card border-0 shadow-sm overflow-hidden" style={{ borderRadius: 12 }}>
          <div className="table-responsive">
            <table className="table table-hover align-middle mb-0">
              <thead className="table-light">
                <tr>
                  <th>ID</th>
                  <th>Well Name</th>
                  <th>District</th>
                  <th>Severity</th>
                  <th>Message</th>
                  <th>Date</th>
                  {isAdmin && <th>Action</th>}
                </tr>
              </thead>
              <tbody>
                {rows.length === 0 ? (
                  <tr>
                    <td colSpan={isAdmin ? 7 : 6} className="text-center py-5 text-muted">
                      <strong>No active alerts.</strong> All wells are within safe thresholds.
                    </td>
                  </tr>
                ) : (
                  rows.map((a) => (
                    <tr key={a.alert_id} className="border-bottom border-light">
                      <td>{a.alert_id}</td>
                      <td className="fw-bold">{a.well_name}</td>
                      <td>{a.district}</td>
                      <td>
                        <span className={`badge ${getSeverityBadge(a.severity)} px-3 py-1.5 fw-bold text-uppercase`} style={{ letterSpacing: '0.5px' }}>
                          {a.severity}
                        </span>
                      </td>
                      <td style={{ fontSize: 13, color: '#4b5563' }}>{a.message}</td>
                      <td className="small text-muted">{new Date(a.created_at).toLocaleString()}</td>
                      {isAdmin && (
                        <td>
                          <button className="btn btn-sm btn-success fw-bold px-3 py-1.5 shadow-sm" onClick={() => openResolveModal(a.alert_id)}>
                            Resolve
                          </button>
                        </td>
                      )}
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      ) : (
        <div className="card border-0 shadow-sm overflow-hidden" style={{ borderRadius: 12 }}>
          <div className="table-responsive">
            <table className="table table-hover align-middle mb-0">
              <thead className="table-light">
                <tr>
                  <th>ID</th>
                  <th>Well Name</th>
                  <th>District</th>
                  <th>Severity</th>
                  <th>Resolution Note</th>
                  <th>Assigned To</th>
                  <th>Resolved Date</th>
                </tr>
              </thead>
              <tbody>
                {history.length === 0 ? (
                  <tr>
                    <td colSpan="7" className="text-center py-5 text-muted">No resolved alerts found.</td>
                  </tr>
                ) : (
                  history.map((h) => (
                    <tr key={h.history_id} className="border-bottom border-light">
                      <td>{h.alert_id}</td>
                      <td className="fw-bold">{h.well_name}</td>
                      <td>{h.district}</td>
                      <td>
                        <span className={`badge ${getSeverityBadge(h.severity)} px-3 py-1.5 fw-bold text-uppercase`}>
                          {h.severity}
                        </span>
                      </td>
                      <td style={{ fontSize: 13, maxWidth: 300 }}>
                        <div className="fw-semibold text-secondary">Note:</div>
                        <div className="text-muted">{h.resolution_note || 'No note provided'}</div>
                      </td>
                      <td><span className="badge bg-secondary px-2">{h.assigned_to}</span></td>
                      <td className="small text-muted">{new Date(h.resolved_at).toLocaleString()}</td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Resolution Form Dialog Modal */}
      {resolveId && (
        <div className="modal show d-block" style={{ backgroundColor: 'rgba(0,0,0,0.5)', zIndex: 1060 }}>
          <div className="modal-dialog modal-dialog-centered">
            <form onSubmit={handleResolve} className="modal-content border-0 shadow-lg p-0" style={{ borderRadius: 14 }}>
              <div className="modal-header bg-success text-white border-0 py-3 px-4">
                <h5 className="modal-title fw-bold">Resolve Alert</h5>
                <button type="button" className="btn-close btn-close-white" onClick={() => setResolveId(null)}></button>
              </div>
              <div className="modal-body p-4">
                <div className="mb-3">
                  <label className="form-label small fw-bold">Assigned To</label>
                  <input className="form-control" placeholder="e.g. John" value={assigned} onChange={(e) => setAssigned(e.target.value)} required />
                </div>
                <div className="mb-3">
                  <label className="form-label small fw-bold">Resolution Notes</label>
                  <textarea rows="4" className="form-control" placeholder="Describe the actions taken" value={note} onChange={(e) => setNote(e.target.value)} required></textarea>
                </div>
              </div>
              <div className="modal-footer border-0 p-3 bg-light d-flex gap-2 justify-content-end">
                <button type="button" className="btn btn-secondary px-3" onClick={() => setResolveId(null)}>Cancel</button>
                <button type="submit" className="btn btn-success px-4 fw-bold">Resolve Alert</button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
